### ISSUE TITLE
Creating store: Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by nbotalov** [redux-observable/redux-observable#136] opened 2016-10-27 15:52 UTC
I'm trying to add redux-observable to existing project on react, redux and redux-thunk.

epics.js
```
import 'rxjs'
import { ajax } from 'rxjs/observable/dom/ajax'

export default function loading$ (action$) {
    action$.ofType(INIT)
        .mergeMap(action => ajax.getJSON(ENDPOINT))
        .map(getFromServer)
};
```

in store.js
```
import epic from './src/actions/epics'

const epicMiddleware = createEpicMiddleware(epic);
const middlewares = [thunk, epicMiddleware];
const appStore = createStore(
    combineReducers({
            ..
        }),
    applyMiddleware(...middlewares));
```

in package.json
```
"redux": "^3.5.2",
"redux-thunk": "^2.1.0",
"redux-observable": "^0.12.1",
"rxjs": "^5.0.0-rc.1"
```

Got error on creating store
**Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined** 
Error throw at subscribeToResult(outerSubscriber, result, outerValue, outerIndex), line
```
else if (typeof result[iterator_1.$$iterator] === 'function') {
```
Have no ideas howto go further

**Comment by istarkov** [comment] 2016-10-27 16:19
Seems duplicate of #68
You forgot `return` at function `return action$.ofType(INIT)`

**Comment by rgbkrk** [comment] 2016-10-27 19:42
Is there any way to provide a better error when people inevitably do this? We'd be checking for the epic returning `undefined`, no? That doesn't seem like too great a cost at startup.

**Comment by jayphelps** [comment] 2016-10-27 20:47
@rgbkrk yeah, we'll need add that to `combineEpics` and again inside the middleware.

**Comment by rgbkrk** [comment] 2016-10-27 21:22
Cool, I'll make a PR.

**Comment by jayphelps** [comment] 2016-10-27 21:46
@rgbkrk if you haven't already started: I've got one nearly done (finishing tests), got caught up in a meeting.

**Comment by rgbkrk** [comment] 2016-10-27 21:54
I was going to start just now, had to wrap up some other things for work.

**Comment by jayphelps** [comment] 2016-10-27 22:43
#137

**Closed** 2016-10-28 03:21 UTC

**Comment by nbotalov** [comment] 2016-10-28 06:34
Thanks!
