### ISSUE TITLE
Type definition of Epic<T = Action,S,D = any> is wrong?

### ISSUE THREAD

**Issue by kyasbal-1994** [redux-observable/redux-observable#392] opened 2018-01-05 06:19 UTC
**Do you want to request a *feature* or report a *bug*?**  

BUG

**What is the current behavior?**

Type definition should be provided correctly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsbin.com or similar.**

I think Type definitions of `redux-observable` is wrong.

```ts
export declare interface Epic<T extends Action, S, D = any> {
  (action$: ActionsObservable<T>, store: MiddlewareAPI<S>, dependencies: D): Observable<T>;
}
```

You can reproduce type error with following code.

```ts
enum ActionTypes{
     EXAMPLE_ACTION = "EXAMPLE_ACTION",
     EXAMPLE_ACTION2 = "EXAMPLE_ACTION2"
}

interface IState{

}

interface IExampleAction extends Action{
   type: ActionTypes.EXAMPLE_ACTION;
}

interface IExampleAction2 extends Action{
   type: ActionTypes.EXAMPLE_ACTION2;
}

type Actions = IExampleAction | IExampleAction2;

function createAction2():IExampleAction2{
   return {
      type: ActionTypes.EXAMPLE_ACTION2
   };
}

export const sampleEpic: Epic<IExampleAction, IState, any> = (action$: ActionsObservable<IExampleAction>, store: MiddlewareAPI<IState>) =>
    action$.ofType(ActionTypes.EXAMPLE_ACTION)
        .mapTo(createAction2())
```

This code should be generate following error.

```
        [ts]
Type '(action$: ActionsObservable<IExampleAction>, store: MiddlewareAPI<IState>) => Observable<IExample...' is not assignable to type 'Epic<IExampleAction, IState, any, IExampleAction>'.
  Type 'Observable<IExampleAction2>' is not assignable to type 'Observable<IExampleAction>'.
    Type 'IExampleAction2' is not assignable to type 'IExampleAction'.
      Types of property 'type' are incompatible.
        Type 'ActionTypes.EXAMPLE_ACTION2' is not assignable to type 'ActionTypes.EXAMPLE_ACTION'.
```

**What is the expected behavior?**

I guess declaration of Epic should be like this.

```ts
export declare interface Epic<T extends Action, S, D = any, O extends Action = T> {
  (action$: ActionsObservable<T>, store: MiddlewareAPI<S>, dependencies: D): Observable<O>;
}
```

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

**Comment by jayphelps** [comment] 2018-01-05 06:20
Hey there, thanks for reporting! Can you describe what in the type signature is wrong specifically?

**Comment by kyasbal-1994** [comment] 2018-01-05 08:42
@jayphelps Thank you for replying me rapidly.
I think an epic can return an observable that returns another type of action.

I think ping pong example is good for describing this problem.

```ts
const pingEpic = action$ =>
  action$.ofType('PING')
    .delay(1000) // Asynchronously wait 1000ms then continue
    .mapTo({ type: 'PONG' });
```

In this exmaple, the input is `ActionObservable<{type:'PING'}>` and output is `Observable<{type:'PONG'}>`.  When we use current definition of Epic, we should make these type corresponded with.

**Comment by jayphelps** [comment] 2018-01-05 23:27
@kyasbal-1994 I think this is a duplicate of #219 and #390, can you confirm?

The major point is that, although it might not be obvious, an epic always recursively receives any actions itself emits, as well as every other action dispatched. It is true that you most often will filter them out with `ofType`, but that's not *always* the case so we can't make that assumption.

I still think there would be benefit being able to specify output actions separately since they are indeed a subset. But no matter what I try TypeScript doesn't seem to correctly type check the return value generic param. It makes me have an Observable, but doesn't care what type it is.

https://gist.github.com/jayphelps/9c527880a16b1470e22c6006a584d7b3

I have to think that this isn't a bug in TS but rather something in the type definitions of redux-observable or rxjs cause TS to not care, possibly because of structural typing vs nominal but I don't see anything.

**Comment by moajo** [comment] 2018-01-07 16:29
@jayphelps 
In this example, no type error occurs because type parameter `T` is not used in `Observable<T>` definition.
In TypeScript,function return type is **covariant** and arguments is **bivariant** .
Therefore, the type of the return value must be compatible.
For example, add a function declaration to the `Observable` type definition as follows.

```
declare class Observable<T> {
  mapTo<T, R>(this: Observable<T>, value: R): Observable<R>;
  someFunc(arg:T):any; // this function use T as argument.
}
```
Then an error will occur.

```
function pingEpic(action$: ActionsObservable<Actions>): Observable<OutputActions> {
  return action$.ofType<PingAction>('PING')
    .mapTo<PingAction, PongAction>({ type: 'PONG' }); // Error:Type 'Observable<PongAction>' is not assignable to type Observable<OutputActions>.
}
```
This is equivalent to replacing the definition with `import` statement as follows.
```
import { Observable } from "rxjs/Observable";
// declare class Observable<T> {
//   mapTo<T, R>(this: Observable<T>, value: R): Observable<R>;
// }
```

**Comment by moajo** [comment] 2018-01-07 16:51
Also for the problem that EPIC receives actions recursively, the return type must be a subset of the input.

The definition of Epic proposed by @kyasbal-1994  should be modified as follows.

```
export declare interface Epic<T extends Action, S, D = any, O extends T = T> {
  (action$: ActionsObservable<T>, store: MiddlewareAPI<S>, dependencies: D): Observable<O>;
}
```

**Comment by jayphelps** [comment] 2018-01-07 18:45
@moajo cool! can you submit a PR with a test in https://github.com/redux-observable/redux-observable/blob/master/test/typings.ts ?

**Comment by moajo** [comment] 2018-01-08 07:43
@jayphelps sure!
i have submitted PR: https://github.com/redux-observable/redux-observable/pull/396

**Closed** 2018-01-12 21:16 UTC
