### ISSUE TITLE
Feature: optional allow combineEpics({ pingEpic }) 

### ISSUE THREAD

**Issue by jaunkst** [redux-observable/redux-observable#325] opened 2017-09-14 07:00 UTC
**Feature request**  
I would like to be able to * import all of the exported epics and combine them. This is allowed by the combineReducers function in redux.

**What is the current behavior?**
```
import { pingEpic } from './state/root/epics'
combineEpics(
    pingEpic
)
```

**What is the expected behavior?**
```
import * as manyEpics from './state/root/epics'
combineEpics(manyEpics)
```
or
```
import { pingEpic } from './state/root/epics'

combineEpics({
    pingEpic
})
```

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

**Comment by jayphelps** [comment] 2017-09-14 17:54
Hey @jaunkst. This is a duplicate of #58, which contains an explanation of why this wasn't supported (it would be misleading). We may support it anyway someday, but you can get the same effect with [`Object.values`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values)

```js
import * as epics from './epics';
// const epics = require('./epics');

const rootEpic = combineEpics(...Object.values(epics));
// or this, same thing
const rootEpic = combineEpics.apply(undefined, Object.values(epics));
```

**Closed by jayphelps** 2017-09-14 17:54 UTC

**Comment by jaunkst** [comment] 2017-09-14 22:17
:ok_hand:
