### ISSUE TITLE
ability to combine epics from an array or object

### ISSUE THREAD

**Issue by b3bakyt** [redux-observable/redux-observable#179] opened 2017-01-25 04:37 UTC
It would be handy to be able to combine Epics from an array or object of epics, for example:

```
import { combineEpics } from 'redux-observable';
import * as epics from './myListOfEpics';

export default combineEpics(epics);
```

in this case we might be able to generate epics dynamically.

**Comment by jayphelps** [comment] 2017-01-25 04:45
Hey 👋 this is a duplicate of https://github.com/redux-observable/redux-observable/issues/58

**Closed by jayphelps** 2017-01-25 04:45 UTC
