### ISSUE TITLE
typescript: pipe operator changes in rxjs 6.3.0 break ofType operator

### ISSUE THREAD

**Issue by duvet86** [redux-observable/redux-observable#569] opened 2018-08-31 14:00 UTC
After updating to rxjs 6.3.0 I got few epics failing when narrowing the action using the ofType operator.

```
export const loginEpic = (action$: ActionsObservable<LoginAction>) =>
  action$.pipe(
    // ofType<ILoginRequest>(LoginActionTypes.LOGIN_REQUEST), <-- TS COMPLAINING HERE
    filter(
      (action): action is ILoginRequest =>
        action.type === LoginActionTypes.LOGIN_REQUEST
    ),
    mergeMap(({ username, password }) =>
      getTokenAsync(username, password).pipe(
        mergeMap(token => [
          // Fire 2 actions, one after the other
          storeTokenAndTriggerLogingSucces(token),
          push("/")
        ]),
        catchError(error => of(loginError(error)))
      )
    )
  );
```
This is the error:
![image](https://user-images.githubusercontent.com/5604548/44916483-7111dc00-ad68-11e8-9901-14c08b3dbc68.png)

I was able to suppress the error using the rxjs filter operator as you can see on the code snip.
I believe this is the change that breaks the ofType operator.
https://github.com/ReactiveX/rxjs/pull/3945

**Comment by jayphelps** [comment] 2018-09-02 02:55
@duvet86 thanks for reporting! I'll try to look into this as soon as I can. If you have a chance to create an easy way to reproduce, e.g. stackblitz is awesome: https://stackblitz.com/edit/redux-observable-v1-playground-typescript I could find a solution much more quickly. I can't immediately reproduce myself.

**Comment by duvet86** [comment] 2018-09-04 07:43
Ok, I couldn't reproduce it online.
So I created a local project with your app.
As soon as I added a tsconfig.json with the "strict": true /* Enable all strict type-checking options. */
the warning popped up.

```
Argument of type '(source: Observable<PingAction>) => Observable<PingAction>' is not assignable to parameter of type 'OperatorFunction<Actions, PingAction>'.
  Types of parameters 'source' and 'source' are incompatible.
    Type 'Observable<Actions>' is not assignable to type 'Observable<PingAction>'.
      Type 'Actions' is not assignable to type 'PingAction'.
        Type 'PongAction' is not assignable to type 'PingAction'.
          Types of property 'type' are incompatible.
            Type '"PONG"' is not assignable to type '"PING"'.
```

This is my package.json:
```
{
  "name": "asd",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "redux": "^4.0.0",
    "redux-observable": "^1.0.0",
    "rxjs": "^6.3.1",
    "typescript": "^3.0.3"
  }
}
```

**Comment by duvet86** [comment] 2018-09-04 08:45
So after a little bit of playing and pondering about the ofType typescript signature I was able to fix the issue defining T and R, where 
`ofType<T extends Action, R extends T = T, K extends R['type'] = R['type']>(...key: K[]): (source: Observable<T>) => Observable<R>;` 
as it follows:

```
export const pingEpic: Epic<Actions, PongAction> = action$ =>
  action$.pipe(
    ofType<Actions, PingAction>("PING"),
    // filter((action): action is PingAction => action.type === "PING"),
    delay(1000),
    map(() => pong())
  );
```

**Comment by Verbon** [comment] 2018-09-13 10:04
Having the similar issue - after updating rxjs from 6.2 to 6.3 all of my epics got broken.

![image](https://user-images.githubusercontent.com/9406367/45481430-2c1c7b00-b754-11e8-8282-2ac3708328f6.png)

Here's my code:
```
export const authorizeUserEpic: SchoolScheduleEpic =
    (action$, _, { authorizationService }) => action$.pipe(
        filter(isActionOf(actions.authorizeUserRequest)),
        concatMap(action => {
            const { username, password } = action.payload;

            const prepareForAuthorizing$ = of(actions.authorizing());
            const authorizeUser$ = from(authorizationService.authorizeUserAsync(username, password)).pipe(
                switchMap(authorizeUserServiceResult => {
                    if (!authorizeUserServiceResult.isSuccessful) {
                        return of(actions.authorizationError());
                    }
                    const { user, accessToken, refreshToken } = authorizeUserServiceResult.result;

                    return of(
                        actions.signInUser(user, accessToken, refreshToken),
                        actions.authorizationSuccess(),
                        actions.fetchUserLinkedPersonRequest()
                    );
                })
            );

            return prepareForAuthorizing$.pipe(concat(authorizeUser$));
        })
    );
```

And there are 2 errors:
1.
![image](https://user-images.githubusercontent.com/9406367/45481644-ba90fc80-b754-11e8-8c4b-f40f0db51c23.png)

```
[ts]
Type '(action$: ActionsObservable<SchoolScheduleAction>, _: StateObservable<ISchoolScheduleState>, { authorizationService }: ISchoolScheduleEpicDependencies) => Observable<{} | { type: "AUTHORIZING"; }>' is not assignable to type 'Epic<SchoolScheduleAction, SchoolScheduleAction, ISchoolScheduleState, ISchoolScheduleEpicDependencies>'.
  Type 'Observable<{} | { type: "AUTHORIZING"; }>' is not assignable to type 'Observable<SchoolScheduleAction>'.
    Type '{} | { type: "AUTHORIZING"; }' is not assignable to type 'SchoolScheduleAction'.
      Type '{}' is not assignable to type 'SchoolScheduleAction'.
        Type '{}' is not assignable to type '{ type: "UPSERT_ENTITIES"; payload: { entitiesModel: Partial<IEntitiesModel>; }; }'.
          Property 'type' is missing in type '{}'.
```

2. 
![image](https://user-images.githubusercontent.com/9406367/45481797-26736500-b755-11e8-993e-028dd6cd93c6.png)

```
[ts]
Argument of type '(authorizeUserServiceResult: OperationResult<IUserAuthorizationResult>) => Observable<{ type: "AUTHORIZATION_ERROR"; }> | Observable<{ type: "AUTHORIZATION_SUCCESS"; } | { type: "FETCH_USER_LINKED_PERSON_REQUEST"; } | { ...; }>' is not assignable to parameter of type '(value: OperationResult<IUserAuthorizationResult>, index: number) => ObservableInput<{ type: "AUTHORIZATION_ERROR"; }>'.
  Type 'Observable<{ type: "AUTHORIZATION_ERROR"; }> | Observable<{ type: "AUTHORIZATION_SUCCESS"; } | { type: "FETCH_USER_LINKED_PERSON_REQUEST"; } | { type: "SIGN_IN_USER"; payload: { user: User; accessToken: string; refreshToken: string; }; }>' is not assignable to type 'ObservableInput<{ type: "AUTHORIZATION_ERROR"; }>'.
    Type 'Observable<{ type: "AUTHORIZATION_SUCCESS"; } | { type: "FETCH_USER_LINKED_PERSON_REQUEST"; } | { type: "SIGN_IN_USER"; payload: { user: User; accessToken: string; refreshToken: string; }; }>' is not assignable to type 'ObservableInput<{ type: "AUTHORIZATION_ERROR"; }>'.
      Type 'Observable<{ type: "AUTHORIZATION_SUCCESS"; } | { type: "FETCH_USER_LINKED_PERSON_REQUEST"; } | { type: "SIGN_IN_USER"; payload: { user: User; accessToken: string; refreshToken: string; }; }>' is not assignable to type 'Iterable<{ type: "AUTHORIZATION_ERROR"; }>'.
        Property '[Symbol.iterator]' is missing in type 'Observable<{ type: "AUTHORIZATION_SUCCESS"; } | { type: "FETCH_USER_LINKED_PERSON_REQUEST"; } | { type: "SIGN_IN_USER"; payload: { user: User; accessToken: string; refreshToken: string; }; }>'.
```

Reverting rxjs to 6.2 fixes the issue, and this code compiles just fine.

**Comment by jayphelps** [comment] 2018-09-17 18:38
Is it possible for someone to provide a complete reproduction, including all types, functions, etc?

**Comment by nzacca** [comment] 2018-10-27 23:53
@jayphelps Here's a very slimmed down version of something similar to what we have in production that broke after attempting to upgrade to 6.3: https://stackblitz.com/edit/redux-observable-v1-playground-typescript-njd2x8?file=ping-pong.ts

Line 24 is where the error is for us and it seems like it has to do with mixing the types within the `catchError`. I don't think any of the other operators matter.

If you need any other information, let me know.

**Comment by irbrownie** [comment] 2018-10-31 16:05
I am also having this issue with rxjs 3.3 and redux-observable 1. I specifically get the symbol.iterator missing  when attempting to concatMap, mergeMap

**Comment by seniorquico** [comment] 2018-11-02 18:22
I pushed an example repo that uses the code from the Troubleshooting guide that demonstrates the error. It looks like I can confirm this error occurs only when using the `strict` compiler option.

https://github.com/seniorquico/redux-observable-569

Current workarounds are either disabling the `strict` compiler option or providing both the `T` and `R` generic type arguments to `ofType`:

```javascript
action$.pipe(
  ofType<Actions, One>(ActionTypes.One),
  map(action => { ... // action type is correctly narrowed
```

Thanks, @duvet86!

**Comment by maxkostow** [comment] 2018-11-20 19:05
@irbrownie I worked around that by specifying the types those like `mergeMap<T, R>`

**Comment by evertbouw** [comment] 2018-11-27 10:46
This seems related https://github.com/ReactiveX/rxjs/issues/4387

**Comment by jayphelps** [comment] 2019-10-19 01:11
Almost a year later, but wanted to reply that @nzacca's example was great, thank you! This turned out to be an issue with RxJS's types. Can't recall which version fixed this, but "it is now fixed". Lmk if anyone here still experiences this.

**Closed by jayphelps** 2019-10-19 01:11 UTC

**Comment by apoorvmote** [comment] 2019-10-19 05:22
I am still having same error. I tried every possible filter operator.

`import { Action } from "redux";
import { ActionsObservable, ofType, combineEpics } from 'redux-observable'
import { map } from 'rxjs/operators'

export enum ActionTypes {
    One = 'ACTION_ONE',
    Two = 'ACTION_TWO'
}

export interface One extends Action {
    type: ActionTypes.One
    myStr: string
}

export const doOne = (myStr: string): One => ({ type: ActionTypes.One, myStr })

export interface Two extends Action {
    type: ActionTypes.Two
    myBool: boolean
}

export const doTwo = (myBool: boolean): Two => ({ type: ActionTypes.Two, myBool })

export type Actions = One | Two

export const epic = (action$: ActionsObservable<Actions>) => 
    action$.pipe(
        ofType<Actions, One>(ActionTypes.One),
        map((action: any) => ({
            type: ActionTypes.Two,
            myBool: true
        }))
    )

export const rootEpic = combineEpics(epic)`

`import { createEpicMiddleware } from "redux-observable"
import { createStore, applyMiddleware } from "redux"
import { reducer } from "./reducer"
import { rootEpic } from "./epic"

export const configStore = () => {

    const epicMiddleware = createEpicMiddleware()

    const store = createStore(reducer, applyMiddleware(epicMiddleware))

    epicMiddleware.run(rootEpic)

    return store
} `

Argument of type '(action$: ActionsObservable<Actions>) => Observable<{ type: ActionTypes; myBool: boolean; }>' is not assignable to parameter of type 'Epic<Action<any>, Action<any>, void, any>'.
  Types of parameters 'action$' and 'action$' are incompatible.
    Type 'ActionsObservable<Action<any>>' is not assignable to type 'ActionsObservable<Actions>'.
      Type 'Action<any>' is not assignable to type 'Actions'.
        Property 'myBool' is missing in type 'Action<any>' but required in type 'Two'.  TS2345

**Comment by jayphelps** [comment] 2019-10-19 06:07
@apoorvmote Your error looks different than the ones described here—yours is about your epic’s function signature whereas this ticket is about the ofType operator.

Your issue is that you declare action$ as an ActionsObservable but no generic param. I recommend taking a look at the Epic interface we export instead of using parameter types.

**Comment by apoorvmote** [comment] 2019-10-19 06:30
@jayphelps 
My errors started with ofType Error. Which I used this thread to solve it. But still its not error free.

```
export type Actions = One | Two
(action$: ActionsObservable<Actions>
```
I have exported both of my actions and use that as union. Its the Github formatting swallowed everything inside brackets. 
 If you get a chance to get on computer. Then please checkout my [public git repo](https://github.com/apoorvmote/epics). I would really appreaciate it. I am not able to add payload without errors. Without payload its working fine.

**Comment by apoorvmote** [comment] 2019-10-19 09:50
@jayphelps 
I was able to get it working by setting (action$: any) instead of (action$: ActionsObservable<Actions>) . Everything works as expected. Also no more ofType error. 

I am also getting same error for state$: StateObservable<StoreState> and again I was able to get it working by setting state$: any. 

Not perfect typescript solution but at least it works.
